# Generated by Django 3.0.5 on 2020-04-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_text', models.TextField(max_length=250, verbose_name='Short Text')),
                ('image', models.ImageField(upload_to='')),
                ('seo_title', models.CharField(max_length=200)),
                ('seo_description', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
