# Generated by Django 3.0.5 on 2020-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200503_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Draft'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
