# Generated by Django 3.0.5 on 2020-05-12 13:27

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200510_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_alt', models.CharField(blank=True, max_length=200)),
                ('img_title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=blog.models.get_image_filename, verbose_name='Image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
